name: Build C# Project and Publish .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./output --self-contained --runtime win-x64

    - name: Check output folder
      run: |
        if (Test-Path "./output") {
          Write-Host "Output folder exists!"
        } else {
          Write-Host "Output folder not found!"
          exit 1
        }

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MyApp-Exe
        path: ./output/*
